[package]
name = "daemon"
version = "0.1.0"
authors = ["dikuchan <dikuchan@yahoo.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }

async-std = "1.9"
bincode = "1.3"
chrono = "0.4"
log = "0.4"
simple-logging = "2.0"

[dev-dependencies]
home = "0.5.3"
