[package]
name = "common"
version = "0.1.0"
authors = ["dikuchan <dikuchan@yahoo.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
chrono = "0.4"
home = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
